version: '3'
services:
  app:
    build: ./python3
    depends_on:
      - db
    volumes:
      - ../application:/var/www
      - ../logs/uwsgi:/var/log/uwsgi
    container_name: uwsgi

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ../logs/nginx:/var/log/nginx
    container_name: nginx

  db:
    build: ./mysql
    ports:
      - "13306:3306"
    env_file: .env.develop
    volumes:
      - ../data/mysql:/var/lib/mysql
      - ../logs/mysql:/var/log/mysql
    container_name: db

  cache:
    build: ./redis
    ports:
      - "16379:6379"
    volumes:
      - ../data/redis:/data
    container_name: cache
